In [2]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup, Comment
import requests as rq

In [3]:
url = 'https://www.basketball-reference.com/'
req = rq.get(url)
page = BeautifulSoup(req.text, 'html.parser')
#print(page)

In [4]:
data = []
for a in page.find_all("tr", class_="full_table"):
    for b in a.find_all("a"):
        if('20' in b["href"]):
            data.append(dict(zip(['team','link'], [b["title"], "http://www.basketball-reference.com" + b["href"]])))
df = pd.DataFrame(data, columns=['team','link'])
df

                      team                                               link
0           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
1          Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
2      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
3          Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
4       Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
5           Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
6          Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
7          New York Knicks  http://www.basketball-reference.com/teams/NYK/...
8       Washington Wizards  http://www.basketball-reference.com/teams/WAS/...
9               Miami Heat  http://www.basketball-reference.com/teams/MIA/...
10           Orlando Magic  http://www.basketball-reference.com/teams/ORL/...
11       Charlotte Hornets  http://www.basketball-reference.com/teams/CHO/...
12           Brooklyn Nets  http://www.basketball-reference.com/teams/BRK/...
13           Atlanta Hawks  http://www.basketball-reference.com/teams/ATL/...
14           Chicago Bulls  http://www.basketball-reference.com/teams/CHI/...
15         Houston Rockets  http://www.basketball-reference.com/teams/HOU/...
16   Golden State Warriors  http://www.basketball-reference.com/teams/GSW/...
17       San Antonio Spurs  http://www.basketball-reference.com/teams/SAS/...
18  Portland Trail Blazers  http://www.basketball-reference.com/teams/POR/...
19  Minnesota Timberwolves  http://www.basketball-reference.com/teams/MIN/...
20          Denver Nuggets  http://www.basketball-reference.com/teams/DEN/...
21    New Orleans Pelicans  http://www.basketball-reference.com/teams/NOP/...
22               Utah Jazz  http://www.basketball-reference.com/teams/UTA/...
23    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
24   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
25      Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
26       Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
27            Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
28        Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
29        Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...

In [126]:
all_links = []
for row in df.itertuples():
    team = row[1]
    link = row[2]
    l = link[0:link.rfind('/')+1]
    for i in range(2015,2019):
        all_links.append(dict(zip(["team","links"],[team,l + str(i) + ".html"])))
#print(all_links)
df_links = pd.DataFrame(all_links, columns=["team","links"])
df_links

                      team                                              links
0           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
1           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
2           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
3           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
4          Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
5          Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
6          Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
7          Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
8      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
9      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
10     Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
11     Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
12         Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
13         Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
14         Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
15         Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
16      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
17      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
18      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
19      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
20          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
21          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
22          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
23          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
24         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
25         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
26         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
27         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
28         New York Knicks  http://www.basketball-reference.com/teams/NYK/...
29         New York Knicks  http://www.basketball-reference.com/teams/NYK/...
..                     ...                                                ...
90               Utah Jazz  http://www.basketball-reference.com/teams/UTA/...
91               Utah Jazz  http://www.basketball-reference.com/teams/UTA/...
92    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
93    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
94    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
95    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
96   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
97   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
98   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
99   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
100     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
101     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
102     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
103     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
104      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
105      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
106      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
107      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
108           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
109           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
110           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
111           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
112       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
113       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
114       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
115       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
116       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...
117       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...
118       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...
119       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...

[120 rows x 2 columns]

In [145]:
def find_comment_index(table,comments):
    index = 0
    for comment in comments:
        if table in comment:
            return index
        index += 1

In [172]:
stats_labels = ['MP','FG','FGA','FG%','3P','3PA','3P%','2P','2PA','2P%','FT','FTA','FT%',
                'ORD','DRB','TRB','AST','STL','BLK','TOV','PF','PTS']

def get_season_per_game_data(link):

    req = rq.get(link)
    page = BeautifulSoup(req.text, 'html.parser')

    comments=page.find_all(string=lambda text:isinstance(text,Comment))
    comm_index = find_comment_index("team_and_opponent",comments)
    #print(comm_index)
    team_opp = BeautifulSoup(comments[comm_index], 'html.parser')
    team_opp
    table_team_opp = team_opp.find("table",id="team_and_opponent")
    column = 0
    data = []
    for r in table_team_opp.find_all('td'):
        if(column >= 24 and column <= 45):
            data.append(float(r.text))
        column += 1
    per_game_data = dict(zip(stats_labels,data))
    return per_game_data

#data_aux = get_season_per_game_data('https://www.basketball-reference.com/teams/BOS/2013.html')


def get_team_stats(team):
    
    data_ = []
    for row in df_links.itertuples():
        if row[1] == team:
            data_.append(get_season_per_game_data(row[2]))
    df_team = pd.DataFrame(data_)
    cols = df_team.columns.tolist()
    cols = stats_labels
    df_team = df_team[cols]
    return df_team

get_team_stats('Minnesota Timberwolves')

,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,...,FT%,ORD,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,241.5,36.4,83.2,0.438,5.0,14.9,0.332,31.5,68.3,0.461,...,0.776,11.6,29.3,40.9,21.6,8.1,4.0,15.0,19.2,97.8
1,242.4,37.7,81.3,0.464,5.5,16.4,0.338,32.2,64.9,0.496,...,0.792,10.0,31.5,41.6,23.4,8.0,4.6,15.0,20.7,102.4
2,241.5,39.5,84.4,0.467,7.3,21.0,0.349,32.1,63.4,0.507,...,0.799,11.4,31.0,42.4,23.7,8.0,4.5,14.0,20.1,105.6
3,241.1,39.9,85.1,0.468,8.3,23.0,0.362,31.5,62.2,0.507,...,0.783,11.0,32.0,43.1,22.7,8.9,3.5,14.3,17.7,107.8

In [173]:
import time

teams = df_links['team'].tolist()
teams_list = list(set(teams))

for team in teams_list:
    print(team)
    time.sleep(0.01)
    df_team = get_team_stats(team)
    team_name = team.replace(" ","_")
    df_team.to_csv('team_stats/' + team_name + '_stats_2014_to_2018.csv')

Detroit Pistons
Atlanta Hawks
Brooklyn Nets
Miami Heat
Dallas Mavericks
Los Angeles Lakers
Phoenix Suns
San Antonio Spurs
Los Angeles Clippers
Milwaukee Bucks
Denver Nuggets
Indiana Pacers
Memphis Grizzlies
New Orleans Pelicans
Boston Celtics
New York Knicks
Sacramento Kings
Oklahoma City Thunder
Philadelphia 76ers
Cleveland Cavaliers
Toronto Raptors
Golden State Warriors
Washington Wizards
Utah Jazz
Charlotte Hornets
Orlando Magic
Houston Rockets
Portland Trail Blazers
Chicago Bulls
Minnesota Timberwolves

In [142]:
def get_roster_info(link):
    url = link
    req = rq.get(url)
    team_page = BeautifulSoup(req.text, 'html.parser')
    i=0
    aux=[]
    name="";
    ht="";
    wt="";
    bday="";
    exp="";
    college="";
    for t in team_page.find_all('table',id="roster"):
        for a in t.find('tbody').find_all('td'):
            if(i==0):
                name=a.text;
            elif(i==2):
                ht=a.text;
            elif(i==3):
                wt=a.text;
            elif(i==4):
                bday=a.text;
            elif(i==6):
                if("R" in a.text):
                    exp=0;
                else:
                    exp=a.text;
            elif(i==7):
                college=a.text;
            i=i+1
            if(i==8):
                i=0;
                aux.append(dict(zip(["name","height","weight","bday","exp","college"],[name,ht,wt,bday,exp,college])))
                name="";
                ht="";
                wt="";
                bday="";
                exp="";
                college="";
    return pd.DataFrame(aux, columns=["name","height","weight","bday","exp","college"])

In [144]:
links = df_links['links'].tolist()

year = 2014
for a in df_links.itertuples():
    team_name = a[1].replace(" ","_")
    df_roster = get_roster_info(a[2])
    df_roster.to_csv('roster_info/' + team_name + '/roster_info_' + str(year) + '-' + str(year+1) + '.csv')
    year += 1
    if year == 2018:
        year = 2014

In [177]:
roster_stats_labels = ['Name','Age','G','GS','MP','FG','FGA','FG%','3P','3PA','3P%','2P','2PA','2P%','eFG%',
                       'FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS/G']

def get_roster_stats(link):
    
    req = rq.get(link)
    page = BeautifulSoup(req.text, 'html.parser')

    comments=page.find_all(string=lambda text:isinstance(text,Comment))
    comm_index = find_comment_index("Per Game Table",comments)
    #print(comm_index)
    per_game_stats = BeautifulSoup(comments[comm_index], 'html.parser')
    table_per_game_stats = per_game_stats.find("table",id='per_game')
    index = 0
    data = []
    row = []
    for r in table_per_game_stats.find_all('td'):
        row.append(r.text)
        index += 1
        if index % 27 == 0:
            data.append(dict(zip(player_stats_labels,row)))
            row = []
    df_roster_stats = pd.DataFrame(data)
    cols = df_roster_stats.columns.tolist()
    cols = roster_stats_labels
    df_roster_stats = df_roster_stats[cols]
    return df_roster_stats

get_roster_stats('https://www.basketball-reference.com/teams/CHI/2018.html')

,Name,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS/G
0,Justin Holiday,28,18,18,34.2,5.1,13.9,.364,2.8,7.7,...,.745,0.6,3.7,4.3,2.1,1.3,0.5,1.3,1.8,14.8
1,Lauri Markkanen,20,19,19,30.6,4.9,12.5,.392,2.5,7.2,...,.792,1.1,7.1,8.2,1.5,0.5,0.6,1.4,1.6,14.3
2,Robin Lopez,29,19,19,29.7,5.6,11.5,.491,0.1,0.4,...,.765,2.8,2.8,5.6,2.1,0.2,0.8,1.8,2.4,12.7
3,Denzel Valentine,24,19,8,28.7,3.9,10.2,.383,2.4,5.6,...,.750,0.7,4.5,5.3,3.1,0.9,0.1,1.1,2.0,10.3
4,Kris Dunn,23,15,6,26.8,4.9,11.7,.415,1.0,2.4,...,.750,0.7,3.9,4.7,4.1,2.1,0.3,3.3,3.2,11.5
5,Jerian Grant,25,19,14,25.9,3.1,7.6,.407,0.7,2.4,...,.824,0.6,2.3,2.9,4.9,0.9,0.1,1.5,1.9,9.2
6,Bobby Portis,22,11,0,22.5,4.6,10.2,.455,1.2,3.3,...,.815,2.0,5.2,7.2,1.7,0.3,0.4,1.5,1.2,12.5
7,David Nwaba,25,8,3,21.0,2.5,4.8,.526,0.3,0.6,...,.722,0.4,5.1,5.5,1.0,0.8,0.8,0.5,1.8,6.9
8,Paul Zipser,23,16,7,16.3,1.4,4.9,.278,0.3,1.8,...,.500,0.2,3.2,3.4,1.1,0.5,0.1,0.9,1.3,3.2
9,Antonio Blakeney,21,9,0,16.1,3.0,8.0,.375,0.8,2.8,...,.706,0.3,1.7,2.0,0.7,0.2,0.0,0.7,0.7,8.1
10,Cristiano Felicio,25,18,0,15.4,1.6,2.7,.571,0.0,0.0,...,.571,1.3,1.8,3.2,0.7,0.2,0.2,0.8,2.3,3.6
11,Quincy Pondexter,29,14,1,11.0,0.9,3.0,.310,0.2,1.4,...,.824,0.5,0.9,1.4,0.4,0.5,0.1,0.6,1.5,3.1
12,Kay Felder,22,12,0,10.5,1.6,5.3,.302,0.3,1.4,...,.900,0.1,0.8,0.9,1.7,0.2,0.1,1.3,0.9,4.3
13,Ryan Arcidiacono,23,1,0,5.0,0.0,2.0,.000,0.0,2.0,...,,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [178]:
year = 2014
for a in df_links.itertuples():
    team_name = a[1].replace(" ","_")
    df_roster_stats = get_roster_stats(a[2])
    df_roster_stats.to_csv('roster_stats/' + team_name + '/roster_stats_' + str(year) + '-' + str(year+1) + '.csv')
    year += 1
    if year == 2018:
        year = 2014