In [1]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup, Comment
import requests as rq

In [2]:
url = 'https://www.basketball-reference.com/'
req = rq.get(url)
page = BeautifulSoup(req.text, 'html.parser')
#print(page)

In [3]:
data = []
for a in page.find_all("tr", class_="full_table"):
    for b in a.find_all("a"):
        if('20' in b["href"]):
            data.append(dict(zip(['team','link'], [b["title"], "http://www.basketball-reference.com" + b["href"]])))
df = pd.DataFrame(data, columns=['team','link'])
df

                      team                                               link
0           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
1      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
2          Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
3          Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
4       Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
5          Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
6           Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
7       Washington Wizards  http://www.basketball-reference.com/teams/WAS/...
8               Miami Heat  http://www.basketball-reference.com/teams/MIA/...
9          New York Knicks  http://www.basketball-reference.com/teams/NYK/...
10       Charlotte Hornets  http://www.basketball-reference.com/teams/CHO/...
11           Orlando Magic  http://www.basketball-reference.com/teams/ORL/...
12           Brooklyn Nets  http://www.basketball-reference.com/teams/BRK/...
13           Atlanta Hawks  http://www.basketball-reference.com/teams/ATL/...
14           Chicago Bulls  http://www.basketball-reference.com/teams/CHI/...
15         Houston Rockets  http://www.basketball-reference.com/teams/HOU/...
16   Golden State Warriors  http://www.basketball-reference.com/teams/GSW/...
17       San Antonio Spurs  http://www.basketball-reference.com/teams/SAS/...
18          Denver Nuggets  http://www.basketball-reference.com/teams/DEN/...
19  Portland Trail Blazers  http://www.basketball-reference.com/teams/POR/...
20  Minnesota Timberwolves  http://www.basketball-reference.com/teams/MIN/...
21               Utah Jazz  http://www.basketball-reference.com/teams/UTA/...
22    New Orleans Pelicans  http://www.basketball-reference.com/teams/NOP/...
23   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
24    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
25            Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
26      Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
27       Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
28        Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
29        Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...

In [4]:
all_links = []
for row in df.itertuples():
    team = row[1]
    link = row[2]
    l = link[0:link.rfind('/')+1]
    for i in range(2015,2019):
        all_links.append(dict(zip(["team","links"],[team,l + str(i) + ".html"])))
#print(all_links)
df_links = pd.DataFrame(all_links, columns=["team","links"])
df_links

                      team                                              links
0           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
1           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
2           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
3           Boston Celtics  http://www.basketball-reference.com/teams/BOS/...
4      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
5      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
6      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
7      Cleveland Cavaliers  http://www.basketball-reference.com/teams/CLE/...
8          Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
9          Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
10         Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
11         Toronto Raptors  http://www.basketball-reference.com/teams/TOR/...
12         Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
13         Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
14         Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
15         Detroit Pistons  http://www.basketball-reference.com/teams/DET/...
16      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
17      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
18      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
19      Philadelphia 76ers  http://www.basketball-reference.com/teams/PHI/...
20         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
21         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
22         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
23         Milwaukee Bucks  http://www.basketball-reference.com/teams/MIL/...
24          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
25          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
26          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
27          Indiana Pacers  http://www.basketball-reference.com/teams/IND/...
28      Washington Wizards  http://www.basketball-reference.com/teams/WAS/...
29      Washington Wizards  http://www.basketball-reference.com/teams/WAS/...
..                     ...                                                ...
90    New Orleans Pelicans  http://www.basketball-reference.com/teams/NOP/...
91    New Orleans Pelicans  http://www.basketball-reference.com/teams/NOP/...
92   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
93   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
94   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
95   Oklahoma City Thunder  http://www.basketball-reference.com/teams/OKC/...
96    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
97    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
98    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
99    Los Angeles Clippers  http://www.basketball-reference.com/teams/LAC/...
100           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
101           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
102           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
103           Phoenix Suns  http://www.basketball-reference.com/teams/PHO/...
104     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
105     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
106     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
107     Los Angeles Lakers  http://www.basketball-reference.com/teams/LAL/...
108      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
109      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
110      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
111      Memphis Grizzlies  http://www.basketball-reference.com/teams/MEM/...
112       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
113       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
114       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
115       Sacramento Kings  http://www.basketball-reference.com/teams/SAC/...
116       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...
117       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...
118       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...
119       Dallas Mavericks  http://www.basketball-reference.com/teams/DAL/...

[120 rows x 2 columns]

In [5]:
def find_comment_index(table,comments):
    index = 0
    for comment in comments:
        if table in comment:
            return index
        index += 1

In [6]:
stats_labels = ['MP','FG','FGA','FG%','3P','3PA','3P%','2P','2PA','2P%','FT','FTA','FT%',
                'ORD','DRB','TRB','AST','STL','BLK','TOV','PF','PTS']

def get_season_per_game_data(link):

    req = rq.get(link)
    page = BeautifulSoup(req.text, 'html.parser')

    comments=page.find_all(string=lambda text:isinstance(text,Comment))
    comm_index = find_comment_index("team_and_opponent",comments)
    #print(comm_index)
    team_opp = BeautifulSoup(comments[comm_index], 'html.parser')
    team_opp
    table_team_opp = team_opp.find("table",id="team_and_opponent")
    column = 0
    data = []
    for r in table_team_opp.find_all('td'):
        if(column >= 24 and column <= 45):
            data.append(float(r.text))
        column += 1
    per_game_data = dict(zip(stats_labels,data))
    return per_game_data

#data_aux = get_season_per_game_data('https://www.basketball-reference.com/teams/BOS/2013.html')


def get_team_stats(team):
    
    data_ = []
    for row in df_links.itertuples():
        if row[1] == team:
            data_.append(get_season_per_game_data(row[2]))
    df_team = pd.DataFrame(data_)
    cols = df_team.columns.tolist()
    cols = stats_labels
    df_team = df_team[cols]
    return df_team

get_team_stats('Minnesota Timberwolves')

,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,...,FT%,ORD,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,241.5,36.4,83.2,0.438,5.0,14.9,0.332,31.5,68.3,0.461,...,0.776,11.6,29.3,40.9,21.6,8.1,4.0,15.0,19.2,97.8
1,242.4,37.7,81.3,0.464,5.5,16.4,0.338,32.2,64.9,0.496,...,0.792,10.0,31.5,41.6,23.4,8.0,4.6,15.0,20.7,102.4
2,241.5,39.5,84.4,0.467,7.3,21.0,0.349,32.1,63.4,0.507,...,0.799,11.4,31.0,42.4,23.7,8.0,4.5,14.0,20.1,105.6
3,241.0,39.6,84.6,0.467,8.3,22.9,0.362,31.3,61.8,0.506,...,0.795,10.8,31.2,42.0,22.6,8.8,3.4,13.9,17.7,107.3

In [173]:
import time

teams = df_links['team'].tolist()
teams_list = list(set(teams))

for team in teams_list:
    print(team)
    time.sleep(0.01)
    df_team = get_team_stats(team)
    team_name = team.replace(" ","_")
    df_team.to_csv('team_stats/' + team_name + '_stats_2014_to_2018.csv')

Detroit Pistons
Atlanta Hawks
Brooklyn Nets
Miami Heat
Dallas Mavericks
Los Angeles Lakers
Phoenix Suns
San Antonio Spurs
Los Angeles Clippers
Milwaukee Bucks
Denver Nuggets
Indiana Pacers
Memphis Grizzlies
New Orleans Pelicans
Boston Celtics
New York Knicks
Sacramento Kings
Oklahoma City Thunder
Philadelphia 76ers
Cleveland Cavaliers
Toronto Raptors
Golden State Warriors
Washington Wizards
Utah Jazz
Charlotte Hornets
Orlando Magic
Houston Rockets
Portland Trail Blazers
Chicago Bulls
Minnesota Timberwolves

In [7]:
def get_roster_info(link):
    url = link
    req = rq.get(url)
    team_page = BeautifulSoup(req.text, 'html.parser')
    i=0
    aux=[]
    name="";
    ht="";
    wt="";
    bday="";
    exp="";
    college="";
    for t in team_page.find_all('table',id="roster"):
        for a in t.find('tbody').find_all('td'):
            if(i==0):
                name=a.text;
            elif(i==2):
                ht=a.text;
            elif(i==3):
                wt=a.text;
            elif(i==4):
                bday=a.text;
            elif(i==6):
                if("R" in a.text):
                    exp=0;
                else:
                    exp=a.text;
            elif(i==7):
                college=a.text;
            i=i+1
            if(i==8):
                i=0;
                aux.append(dict(zip(["name","height","weight","bday","exp","college"],[name,ht,wt,bday,exp,college])))
                name="";
                ht="";
                wt="";
                bday="";
                exp="";
                college="";
    return pd.DataFrame(aux, columns=["name","height","weight","bday","exp","college"])

In [144]:
links = df_links['links'].tolist()

year = 2014
for a in df_links.itertuples():
    team_name = a[1].replace(" ","_")
    df_roster = get_roster_info(a[2])
    df_roster.to_csv('roster_info/' + team_name + '/roster_info_' + str(year) + '-' + str(year+1) + '.csv')
    year += 1
    if year == 2018:
        year = 2014

In [9]:
roster_stats_labels = ['Name','Age','G','GS','MP','FG','FGA','FG%','3P','3PA','3P%','2P','2PA','2P%','eFG%',
                       'FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS/G']

def get_roster_stats(link):
    
    req = rq.get(link)
    page = BeautifulSoup(req.text, 'html.parser')

    comments=page.find_all(string=lambda text:isinstance(text,Comment))
    comm_index = find_comment_index("Per Game Table",comments)
    #print(comm_index)
    per_game_stats = BeautifulSoup(comments[comm_index], 'html.parser')
    table_per_game_stats = per_game_stats.find("table",id='per_game')
    index = 0
    data = []
    row = []
    for r in table_per_game_stats.find_all('td'):
        row.append(r.text)
        index += 1
        if index % 27 == 0:
            data.append(dict(zip(roster_stats_labels,row)))
            row = []
    df_roster_stats = pd.DataFrame(data)
    cols = df_roster_stats.columns.tolist()
    cols = roster_stats_labels
    df_roster_stats = df_roster_stats[cols]
    return df_roster_stats

get_roster_stats('https://www.basketball-reference.com/teams/CHI/2018.html')

,Name,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS/G
0,Justin Holiday,28,21,21,34.2,5.0,13.6,.368,2.8,7.7,...,.769,0.6,3.7,4.2,2.2,1.2,0.6,1.2,2.0,14.7
1,Lauri Markkanen,20,22,22,30.5,5.0,12.7,.393,2.3,6.9,...,.825,1.0,7.0,8.0,1.4,0.6,0.6,1.4,1.8,14.5
2,Robin Lopez,29,22,22,29.7,5.8,11.3,.514,0.1,0.3,...,.762,2.8,2.7,5.5,2.1,0.3,0.8,1.8,2.2,13.2
3,Denzel Valentine,24,22,11,29.1,3.7,9.6,.382,2.2,5.4,...,.667,0.7,4.5,5.3,3.1,0.9,0.1,1.0,2.0,9.7
4,Kris Dunn,23,18,9,27.1,5.0,11.6,.431,1.1,2.4,...,.609,0.7,3.9,4.7,4.4,1.9,0.3,3.2,3.1,11.8
5,Jerian Grant,25,22,14,25.2,3.2,7.6,.423,0.8,2.5,...,.776,0.5,2.3,2.8,4.9,0.9,0.1,1.5,1.9,9.3
6,Bobby Portis,22,13,0,22.4,4.5,10.2,.444,1.2,3.3,...,.793,2.0,5.0,7.0,1.8,0.2,0.4,1.4,1.2,12.0
7,David Nwaba,25,10,3,20.7,2.4,4.7,.511,0.2,0.7,...,.727,0.5,4.9,5.4,1.6,0.7,0.6,0.7,1.8,6.6
8,Paul Zipser,23,19,7,16.6,1.7,5.4,.311,0.5,2.3,...,.500,0.3,3.0,3.3,1.1,0.4,0.2,0.8,1.5,4.0
9,Cristiano Felicio,25,20,0,15.3,1.8,2.9,.621,0.0,0.0,...,.556,1.2,1.8,3.0,0.7,0.2,0.2,0.8,2.1,4.1
10,Antonio Blakeney,21,11,0,14.8,2.5,7.0,.364,0.7,2.5,...,.737,0.3,1.5,1.8,0.6,0.2,0.0,0.7,0.7,7.1
11,Quincy Pondexter,29,15,1,10.5,0.9,2.8,.310,0.2,1.3,...,.824,0.5,0.8,1.3,0.4,0.5,0.1,0.6,1.4,2.9
12,Kay Felder,22,13,0,10.0,1.5,5.0,.308,0.3,1.4,...,.917,0.1,1.0,1.1,1.5,0.2,0.1,1.2,0.8,4.2
13,Ryan Arcidiacono,23,1,0,5.0,0.0,2.0,.000,0.0,2.0,...,,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [178]:
year = 2014
for a in df_links.itertuples():
    team_name = a[1].replace(" ","_")
    df_roster_stats = get_roster_stats(a[2])
    df_roster_stats.to_csv('roster_stats/' + team_name + '/roster_stats_' + str(year) + '-' + str(year+1) + '.csv')
    year += 1
    if year == 2018:
        year = 2014

In [12]:
data_aux = []
i = 0
for a in df_links.itertuples():
    if '2018' in a[2]:
        print('oi' + " " + str(i))
        i += 1
        data_aux.append(get_team_stats(a[1]))

df_aux = pd.DataFrame(dict(zip(stats_labels,data_aux)), columns=stats_labels)
df_aux

oi 0
oi 1
oi 2
oi 3
oi 4
oi 5
oi 6
oi 7
oi 8
oi 9
oi 10
oi 11
oi 12
oi 13
oi 14
oi 15
oi 16
oi 17
oi 18
oi 19
oi 20
oi 21
oi 22
oi 23
oi 24
oi 25
oi 26
oi 27
oi 28
oi 29

ValueError: If using all scalar values, you must pass an index